Expose IsActive and IsHdr for Audio and Video stream infos
ffmpeginteropx/FFmpegInteropX pull request #444
Opened 2024-11-26 17:54 UTC by brabebhin

This PR adds the following properties:
IsActive to VideoStreamInfo and AudioStreamInfo. This is a convenience method for determining which StreamInfo is the active stream info without querying the FFmpegMediaSource.

IsHdr for VideoStreamInfo to determine if a stream has HDR metadata when we use uncompressed providers (Directx or ffmpeg software decoder)

2024-11-26 18:28 UTC, lukasf requested changes
Thanks for the PR! Generally this looks like a good idea.

I have a general remark about the HDR flag, besides the smaller logical errors I commented on. We have a config setting to trigger if HDR Output is enabled, plus a check on the display info, which in the end sets the applyHdrColorInfo boolen flag. Even if HDR Output is disabled, I think we should still correctly report that this is an HDR stream. Because it still is HDR, and it will probably look kind of bad, if it is shown on in SDR.

So my recommendation would be moving the hasHdrMetadata assignment out of the "apply" blocks down to the end of the method, just combining colorPrimaries >= 2020 or transferFunction >= 2020 or lightMetadata or displayMetadata in one condition - no matter if applyHdrMetadata is set or not.

2024-11-26 18:28 UTC, lukasf commented on Source/UncompressedVideoSampleProvider.h
> +        videoStreamInfo.as<implementation::VideoStreamInfo>()->SetIsHdr(true);
Shouldn't this be hasHdrMetadata instead of "true"?

2024-11-26 18:28 UTC, lukasf commented on Source/UncompressedVideoSampleProvider.cpp
> +        hasHdrMetadata = true;
This is actually not correct. If the color_primaries are < BT2020, this is not HDR but SDR. Also for SDR we can have color primaries. This is why we have an or condition with applyHdrColorInfo.

2024-11-26 18:28 UTC, lukasf commented on Source/UncompressedVideoSampleProvider.cpp
> +        hasHdrMetadata = true;
Same as above, there are also color transfer functions for SDR (< 2020).

2024-11-26 18:39 UTC, brabebhin commented
hi @lukasf 

Thanks for the info.
So my understanding of the applyHdrColorInfo flag was kinda wrong after all. ^^

Not sure why I can't relay to your main comment.

2024-11-26 20:05 UTC, brabebhin commented
@lukasf  take a look at the new commit. thanks.

2024-11-27 20:39 UTC, lukasf commented on Source/UncompressedVideoSampleProvider.cpp
> +    hasHdrMetadata = (masteringDisplayMetadata != nullptr && (masteringDisplayMetadata->has_primaries || masteringDisplayMetadata->has_luminance)) || contentLightMetadata != nullptr;
This is missing ` || codecPar->color_primaries >= MFVideoPrimaries_BT2020 || codecPar->color_trc >= MFVideoTransFunc_2020_const`

2024-11-27 21:50 UTC, lukasf approved these changes
Approved, thank you @brabebhin!

2024-11-27 22:09 UTC, merged